### ISSUE TITLE
Encoders in BOM

### ISSUE THREAD

**Issue by ghent360** [XRobots/openDogV3#3]
Hi, are the encoders listed in the bom the ones you use in the video. By looking at the link the specified ones are just AMS magnetic encoder on a PCB with a magnet. The ones I see in your videos look quite different with a whole housing.

**Comment by ghent360** [comment]
Also the magnetic encoders would need a magnet of some sort to be attached to the axis, do these come with the motor board?

**Comment by XRobots** [comment]
I updated the BOM with links, it's this one, and it ships with the magnet: https://www.digikey.co.uk/en/products/detail/AS5047P-TS_EK_AB/AS5047P-TS_EK_AB-ND/5452344

**Comment by ghent360** [comment]
Thank you. I saw you use the boards in one of your other videos.
